### ISSUE TITLE
Pod Disruption Policy Issue

### ISSUE THREAD

**Issue by dhinojosa** [dhinojosa/machine-learning-data-pipelines#15]
Fix needs to be `policy/v1` for confluent chart

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: confluent-oss-cp-zookeeper-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: cp-zookeeper
```
